language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t weirdoal/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true weirdoal/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "eu-west-2"
   app: "Docker-react"
   env: "Dockerreact-env"
   bucket_name: "elasticbeanstalk-eu-west-2-864166960834"
   bucket_path: "Docker-react"
   on:
      branch: main
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
